### ISSUE TITLE
Feature request: Remove dependency to 'progressbar' when running quiet

### ISSUE THREAD

**Issue by n-lohrmann** [bessman/mcbootflash#11]
Hi,

I'm using this application for a Yocto Linux build, performing updates of a PIC24 through SWUpdate. While I'm very happy with the application, i found it a bit messy to add 'progressbar' and its dependencies that are not present in Yocto. So i wrote a patch that removes all references to 'progressbar'. A neat feature would be to skip the import and progressbar functions if running quiet. (Not sure if this is good practice for Python, mostly work in C...)

Thanks again for this excellent piece of code 😄

**Comment by bessman** [comment]
`progressbar2` is now optional as of v6.0.0!
