### ISSUE TITLE
Checksum issue

### ISSUE THREAD

**Issue by evplasmaman** [bessman/mcbootflash#16]
Hello Bessman,

I thought I was having a similar problem to #13. I get the same error message but mine showed up at the very first packet transmission:

[output.txt](https://github.com/bessman/mcbootflash/files/12697290/output.txt)

It turns out that I had forgotten to enable the bootloader checksum command in the MCC. I never caught that before because I think UBHA just ignores it. 

Would it be possible and would you be willing to add a command line flag to disable that check?

Many Thanks!

**Comment by bessman** [comment]
Working on it :smiley:

**Comment by bessman** [comment]
Should work now. Let me know if it doesn't.

**Comment by evplasmaman** [comment]
Works like a charm! Thank you very much!
