### ISSUE TITLE
Where is the upper end of the program memory range?

### ISSUE THREAD

**Issue by bessman** [bessman/mcbootflash#19]
Split from #13.

Problem description
--------------------------

> I am currently using version 7.0.2 and I still have an error. The problemed seems to come when verifying the integrity of the written app. [output.txt](https://github.com/bessman/mcbootflash/files/12717412/output.txt) [mcbootflash.txt](https://github.com/bessman/mcbootflash/files/12717413/mcbootflash.txt)

Analysis
-----------

Looking at the provided readbacks, the problem looks related to those pernicious four final bytes right on the edge of the program memory range. Those are the only four which differ:

![program_memory_range](https://github.com/bessman/mcbootflash/assets/1999462/62f9418c-c56b-4e21-9854-1e2c74942e40)

I had interpreted the *program memory range* (PMR) reported by the bootloader as a half-open range, like Python's `range`. It seems it's actually closed on both ends; UBHA has written 0x5000 to address 0x2B7FE, which is the upper end of the PMR.

Strangely, UBHA seems to have written 0x0000 to address 0x2B7FF, which should be strictly outside the PMR. I would have expected an attempt to write there to fail with BAD_ADDRESS. Could it have something to do with the 24-bit instruction width? Should the odd address after the reported upper memory bound be considered the actual end of the PMR?

Next step
-------------

The upper bound of the PMR reported by the bootloader should be considered valid for writing.

Need to investigate if it is necessary to also attempt to write to one additional address beyond that.

**Comment by bessman** [comment]
Testing confirms that the highest writable address is in fact one beyond the upper bound reported by the bootloader. Weird.

**Comment by bessman** [comment]
@mSavardCatalys Try v7.0.3.

**Comment by mSavardCatalys** [comment]
Works like a charm! Thank you! <3
