### ISSUE TITLE
Flashing failed: BadAddress

### ISSUE THREAD

**Issue by mSavardCatalys** [bessman/mcbootflash#21]
MCU: dsPIC33CH512MP508
mcbootflash version: 7.0.3
Following this issue: https://github.com/bessman/mcbootflash/issues/13
Hi bessman, we are using a new MCU. this time it is the dsPIC33CH256MP508. Same as the previous one but with 512MB instead of 256MB. We are still not able to properly flash it with MCC bootloader. We are able to flash it properly using Microchip Unified Bootloader Host Application v1.19.1 though. Here are the files you previously ask my colleague. Note that "mcbootflash.txt" and "Unified Bootloader Host Application (UBHA).txt" were read using MPLAB and SNAP debugger.

Do not mind asking for further clarification or debug data!

[application.txt](https://github.com/bessman/mcbootflash/files/12834370/application.txt)
[mcbootflash.txt](https://github.com/bessman/mcbootflash/files/12834372/mcbootflash.txt)
[output.txt](https://github.com/bessman/mcbootflash/files/12834374/output.txt)
[UBHA.txt](https://github.com/bessman/mcbootflash/files/12834375/UBHA.txt)

**Comment by bessman** [comment]
Thanks for the report! You guys are really putting mcbootflash through the wringer :sweat_smile: 

At a glance, the failing command tries to write to 0x55c22, which is not aligned with the write size (0x8). That would be my first guess as to why it fails.

**Comment by bessman** [comment]
Yep, that's why.

**Comment by bessman** [comment]
Try v7.0.4.
